//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imgs2Pdf.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imgs2Pdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Drag one or more JPG/PNG files into the window, then press &quot;Convert to PDF&quot; button. 的當地語系化字串。
        /// </summary>
        public static string AppMessage {
            get {
                return ResourceManager.GetString("AppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Convert JPGs to one PDF 的當地語系化字串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto-rotate images. 的當地語系化字串。
        /// </summary>
        public static string AutoRotate {
            get {
                return ResourceManager.GetString("AutoRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear All 的當地語系化字串。
        /// </summary>
        public static string BtnClearAll {
            get {
                return ResourceManager.GetString("BtnClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Convert to PDF 的當地語系化字串。
        /// </summary>
        public static string BtnConvertTitle {
            get {
                return ResourceManager.GetString("BtnConvertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove Selected 的當地語系化字串。
        /// </summary>
        public static string BtnRemoveSelected {
            get {
                return ResourceManager.GetString("BtnRemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image File List 的當地語系化字串。
        /// </summary>
        public static string ImageFileList {
            get {
                return ResourceManager.GetString("ImageFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Official web: 的當地語系化字串。
        /// </summary>
        public static string OfficialWeb {
            get {
                return ResourceManager.GetString("OfficialWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Orientation: 的當地語系化字串。
        /// </summary>
        public static string PageOrientation {
            get {
                return ResourceManager.GetString("PageOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please pick the file name for the outputted PDF 的當地語系化字串。
        /// </summary>
        public static string PdfDialogTitle {
            get {
                return ResourceManager.GetString("PdfDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Landscape 的當地語系化字串。
        /// </summary>
        public static string PdfLandscape {
            get {
                return ResourceManager.GetString("PdfLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PDF Options 的當地語系化字串。
        /// </summary>
        public static string PdfOptions {
            get {
                return ResourceManager.GetString("PdfOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done, the outputted file is 的當地語系化字串。
        /// </summary>
        public static string PdfOutputDone {
            get {
                return ResourceManager.GetString("PdfOutputDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start generating the PDF file, please wait... 的當地語系化字串。
        /// </summary>
        public static string PdfOutputStart {
            get {
                return ResourceManager.GetString("PdfOutputStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Portrait 的當地語系化字串。
        /// </summary>
        public static string PdfPortrait {
            get {
                return ResourceManager.GetString("PdfPortrait", resourceCulture);
            }
        }
    }
}
